version: "3"
services:
  centos:
    container_name: ondemand-docker
    ports:
      - 221:221
      - 80:80
    networks:
      - ondemand-network
    build: ./docker
    privileged: true

networks:
  ondemand-network:
    driver: bridge